AllCops:
  Exclude:
    - 'Guardfile'
    - 'vendor/**'
    - '**/inspec/default_spec.rb'
    - '**/serverspec/default_spec.rb'

AlignParameters:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundBlockBody:
  Enabled: False

Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: true
  Exclude:
    - '**/metadata.rb'
    - 'attributes/**'

Style/FileName:
  Enabled: false
